### ISSUE TITLE
Mars tagline is utter shit - think of better one

### ISSUE THREAD

**Issue by jameslkingsley** [marseditor/mars#63]
> Mars gives players full control over how their mission is played, in real time.

> how their mission is played

> how mission is played

_triggered_

**Comment by 654wak654** [comment]
Severity: Major

**Comment by SchwererKonigstiger** [comment]
**Absolute Control**
Mission Control the way it should be.

**Comment by Neviothr** [comment]
I actually like the current one.

**Comment by jameslkingsley** [comment]
My problem with it is that it's false. Mars doesn't change _how_ a mission is played, that's up to the players on the ground.
