### ISSUE TITLE
Throwing a grenade while RCing will throw your PC's grenade

### ISSUE THREAD

**Issue by SchwererKonigstiger** [marseditor/mars#84]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**Mars Version:** `test release on discord` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@mars`
- `@ACE3`

**Description:**
Throwing a grenade while remote controlling a unit with ACE Advanced Throwing enabled will throw the player's own grenade instead.

**Steps to reproduce:**
- Enable ACE Advanced Throwing
- Remote Control a Unit
- Throw grenade
- Die to bleeding out

**Where did the issue occur?**
- Dedicated 

**RPT log file:**
Not required

**Comment by jameslkingsley** [comment]
rip

**Comment by jonpas** [comment]
I am actually glad people are reporting this zo the right place, thank you! :D

**Comment by jameslkingsley** [comment]
Why this shit isn't default in Arma I don't know. Seems simple enough to update the `remoteControl` command to auto-set the global variable.
